-- ==============================================================================
-- DEPRECATED — do not execute this file
-- ==============================================================================
--
-- Database schema and security changes are maintained exclusively in
-- supabase/migrations/001_initial_schema.sql through
-- supabase/migrations/006_remove_public_insert_policies.sql.
--
-- This former consolidated copy could drift from migrations and accidentally
-- reintroduce old policies or RPC behavior.  It is deliberately a marker file
-- so that no deployment process treats it as an alternative schema source.
-- ==============================================================================
