-- ==============================================================================
-- DEPRECATED — do not run this file
-- ==============================================================================
--
-- The previous all-in-one setup script had diverged from the application schema
-- (including event_moments/image_url versus moments/media_url).  It is retained
-- only as a clear signpost for existing links; it must not be used to provision
-- a database.
--
-- Canonical database source of truth:
--   supabase/migrations/001_initial_schema.sql
--   supabase/migrations/002_rls_and_security.sql
--   supabase/migrations/003_atomic_checkin_rpc.sql
--   supabase/migrations/004_storage_and_realtime.sql
--   supabase/migrations/005_atomic_rsvp_and_group_rpc.sql
--   supabase/migrations/006_remove_public_insert_policies.sql
--
-- Apply those migrations in order with the Supabase CLI or your deployment
-- migration runner.  Do not paste a subset into the SQL editor.
-- ==============================================================================
